### ISSUE TITLE
demo-cgi createDB.py in README

### ISSUE THREAD

**Issue by abel408** [GluuFederation/oxd-python#5]
I am working on getting the demo-cgi application up on my webserver for learning purposes. The README file states the following:

> Run ./createDB.py to initialize the database

There is no createDB.py file. How can I initialize the database? I'm currently getting a cookie error in my apache log when navigating to home.cgi

**Comment by tecoholic** [comment]
The filename was wrongly mentioned in the README. It has been updated to

>  Run `./setupDemo.py` to initialize the database
