### ISSUE TITLE
setupdemo.py in demo-cgi returns errors

### ISSUE THREAD

**Issue by abel408** [GluuFederation/oxd-python#6]
The following errors are returned when trying to initialize the database:

`  File "./setupDemo.py", line 6, in <module>
    from appLog import *
  File "/var/www/cgi-bin/appLog.py", line 6, in <module>
    fh = logging.FileHandler(LOG_FN)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)`

**Comment by tecoholic** [comment]
@abel408 I can't see any error in the text you have posted. Can you post more details.

Also I would suggest,  you look at demosite folder which is a flask application with more human readable code and very neatly laid out example of using oxd-python. We use it to test oxd-python.

**Comment by abel408** [comment]
Thanks tecoholic,

I gave up on the demo-cgi project and set up the demosite that you recommended. I have followed the instructions exact and I am able to bring up the page. When I click the "Go to Authorization Page" I get the following:

`[Thu Mar 30 14:08:40.383917 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'client_name' in section: 'client'
[Thu Mar 30 14:08:40.384318 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'client_jwks_uri' in section: 'client'
[Thu Mar 30 14:08:40.384520 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'client_token_endpoint_auth_method' in section: 'client'
[Thu Mar 30 14:08:40.384716 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'client_id' in section: 'client'
[Thu Mar 30 14:08:40.384967 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'client_secret' in section: 'client'
[Thu Mar 30 14:08:40.385158 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'grant_types' in section: 'client'
[Thu Mar 30 14:08:40.385321 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'acr_values' in section: 'client'
[Thu Mar 30 14:08:40.385480 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'contacts' in section: 'client'
[Thu Mar 30 14:08:40.385865 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'client_logout_uris' in section: 'client'
[Thu Mar 30 14:08:40.386043 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'client_request_uris' in section: 'client'
[Thu Mar 30 14:08:40.386198 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'client_sector_identifier_uri' in section: 'client'
[Thu Mar 30 14:08:40.386349 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'response_types' in section: 'client'
[Thu Mar 30 14:08:40.386499 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'scope' in section: 'client'
[Thu Mar 30 14:08:40.386648 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'ui_locales' in section: 'client'
[Thu Mar 30 14:08:40.386878 2017] [:error] [pid 30437] WARNING:oxdpython.configurer:No option 'claims_locales' in section: 'client'
[Thu Mar 30 14:08:40.508385 2017] [:error] [pid 30437] ERROR:oxdpython.client:OxD Server Error: internal_error
[Thu Mar 30 14:08:40.508580 2017] [:error] [pid 30437] Description:Unknown internal server error occurs.
[Thu Mar 30 14:08:40.509587 2017] [:error] [pid 30437] [remote 10.131.0.227:60651] [2017-03-30 14:08:40,508] ERROR in app: Exception on /authorize/ [GET]
[Thu Mar 30 14:08:40.509726 2017] [:error] [pid 30437] [remote 10.131.0.227:60651] Traceback (most recent call last):
[Thu Mar 30 14:08:40.509809 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
[Thu Mar 30 14:08:40.509866 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]     response = self.full_dispatch_request()
[Thu Mar 30 14:08:40.509918 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
[Thu Mar 30 14:08:40.509969 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]     rv = self.handle_user_exception(e)
[Thu Mar 30 14:08:40.510018 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
[Thu Mar 30 14:08:40.510064 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]     reraise(exc_type, exc_value, tb)
[Thu Mar 30 14:08:40.510105 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
[Thu Mar 30 14:08:40.510148 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]     rv = self.dispatch_request()
[Thu Mar 30 14:08:40.510189 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
[Thu Mar 30 14:08:40.510230 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Mar 30 14:08:40.510271 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]   File "/var/www/openid-demo/oxd-python/demosite/demosite.py", line 27, in authorize
[Thu Mar 30 14:08:40.510312 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]     auth_url = oxc.get_authorization_url()
[Thu Mar 30 14:08:40.510356 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]   File "/var/www/openid-demo/oxd-python/oxdpython/client.py", line 132, in get_authorization_url
[Thu Mar 30 14:08:40.510398 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]     self.register_site()
[Thu Mar 30 14:08:40.510439 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]   File "/var/www/openid-demo/oxd-python/oxdpython/client.py", line 105, in register_site
[Thu Mar 30 14:08:40.510480 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]     self.oxd_id = self.__clear_data(response).oxd_id
[Thu Mar 30 14:08:40.510521 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]   File "/var/www/openid-demo/oxd-python/oxdpython/client.py", line 64, in __clear_data
[Thu Mar 30 14:08:40.510561 2017] [:error] [pid 30437] [remote 10.131.0.227:60651]     raise RuntimeError(error)
[Thu Mar 30 14:08:40.510601 2017] [:error] [pid 30437] [remote 10.131.0.227:60651] RuntimeError: OxD Server Error: internal_error
[Thu Mar 30 14:08:40.510641 2017] [:error] [pid 30437] [remote 10.131.0.227:60651] Description:Unknown internal server error occurs.`


My demosite.cfg file looks like this:
`[oxd]
host = localhost
port = 8099
id = 

[client]
authorization_redirect_uri = https://openid-demo.domain.org/callback
post_logout_redirect_uri = https://openid-demo.domain.org/
op_host = https://sso.domain.org
application_type = web`

Do you have any suggestions on what I can try?

Thanks!

**Comment by nynymike** [comment]
This is not a bug. You'll need to register and open this issue on https://support.gluu.org 
One quick note: did you download and install a license for oxd?
